### ISSUE TITLE
Episode 4  Getting Your project set up with Version Control in RStudio - project Type screen

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#128] opened 2023-12-10 18:49 UTC
Recent version of R studio has a screen in the New Project Wizard where you choose a project type.

This needs to be incorporated into the lesson.

Should user choose the first option: New R Project

or

Quarto Project?

<img width="708" alt="02-rstudio-project-type" src="https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/assets/275899/f1592de6-130c-4d25-a163-cb27b65ef636">

**Comment by rcurty** [comment] 2023-12-10 19:23
We are creating a project from version control, not need to select the quarto option.

**Comment by rcurty** [comment] 2023-12-18 19:11
Add content to mention quarto projects before we cover the project yaml for relative paths. 

See: https://quarto.org/docs/projects/quarto-projects.html

**Comment by rcurty** [comment] 2024-01-12 16:40
Discuss placement. Should we add this when learners are asked to create their first qmd "my-first-qmd", and instead ask them to create a quarto project, so that we can cover the files and settings?

**Comment by torwhite** [comment] 2024-01-26 18:48
That could work! But let's make sure not to over-burden learners at that beginning stage.

**Comment by ilessing** [comment] 2024-01-26 19:37
suggested in meeting today:

tell learners that you can still make Quarto documents inside a generic Rstudio project OR in a Quarto Project.   It is not necessary  to create a Quarto project to use Quarto documents in your project.

Since we are not having learners create a brand new project from scratch they do NOT have to make the choice about project type during the workshop.  For this reason we can cover Quarto project topics like the Project YAML (`_quarto.yml`) in later episode/advanced topics.

**Comment by rcurty** [comment] 2024-01-26 22:23
Suggestion for placement: at the end of episode https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/02-Quarto/02-setup-versioning/index.html to cause less disruption.

A note on Quarto projects:
When initiating a new project, you have the option to open a Quarto project, as illustrated in the image below (add fig). Regardless of your choice, you can create new Quarto documents within R projects, Quarto projects, or even outside projects at any time. You may be curious about the distinctions and advantages of using Quarto Projects.
Quarto projects offer efficient file rendering within a directory, support shared YAML configuration across documents, and provide flexibility in redirecting outputs to a specified directory. Every Quarto project includes a "_quarto.yml" configuration file, ensuring that any document rendered within the project directory automatically inherits the metadata defined at the project level. However, there's no need to worry about this now. Let's focus on the basics first, and we'll explore more advanced features of Quarto projects later on.

**Comment by torwhite** [comment] 2024-01-26 23:47
I think that the note on Quarto projects should be in the "Method #1" section (though perhaps a callout at the end of that section) rather than at the end of the episode. The screenshot of the project menu needs to be added to Method 1 instructions regardless and adding the note at the end would require adding the figure twice. 

Edit to the note: 

"When initiating a new project, you are presented with a large variety of project options from a generic “New Project” (aka R Project) to a variety of Quarto projects as seen in the image above (add fig). Regardless of your choice at this step, you can create new Quarto documents within R projects, Quarto projects, or even outside projects at any time. You may also convert an R project to a Quarto project and back at any point as well. 

However, there's no need to worry too much about this now. Let's focus on the basics first, and we'll explore more advanced features of Quarto projects in a later episode."

I don't think we need to mention the "_quarto.yml" file at this point. I will do a callback to this menu when I introduce Quarto projects in the Advanced episode and introduce/expand on "_quarto.yml" then

**Comment by rcurty** [comment] 2024-01-27 00:23
@torwhite The challenge is that the whole episode and the methods covered are about version control which does not apply to quarto projects. I guess I will add a separate heading "Creating projects in Rstudio" where it does not get mixed with the methods for version control.

**Comment by rcurty** [comment] 2024-01-27 00:43
Please see changes: https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/commit/237170758abe84f0bafcd3a21bc64c946046e074. 
I made a few tweaks to help with the flow.

**Comment by torwhite** [comment] 2024-01-27 01:23
There seems to be an issues with the page because it's not rendering properly for me - just a giant block of text!

**Comment by rcurty** [comment] 2024-01-27 01:51
9c29129

**Comment by rcurty** [comment] 2024-01-30 22:08
Closing this after creating a new issue specifying required actions: Reorg Git/GitHub content #148

**Closed as completed by rcurty** 2024-01-30 22:08 UTC
