### ISSUE TITLE
Discrepancies on project file structure example

### ISSUE THREAD

**Issue by brunj7** [UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto#80] opened 2023-06-22 17:19 UTC
There is a mismatch between the project example between the [figure](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/bucket1_review/fig/04-directory-tree.png) in the document and the [file structure](https://github.com/carpentries-incubator/Reproducible-Publications-with-RStudio-Example/tree/quarto) in the project management [episode](https://github.com/UCSBCarpentry/Reproducible-Publications-with-RStudio-Quarto/blob/bucket1_review/_episodes/01-Project-Setup-Organization/02-good-project.md)

I am unsure if it was an intentional simplification or a version mismatch...

**Comment by rcurty** [comment] 2023-10-27 17:26
Assigning to @brunj7 since it relates to other issues he is handling #64 and #66

**Comment by ilessing** [comment] 2023-10-27 18:46
in meeting today Torin said they thought the mismatch was due to leftover when we reorganized file structure some time ago

**Comment by rcurty** [comment] 2023-10-27 18:49
See #90

**Comment by rcurty** [comment] 2023-11-22 21:41
Those are resolved. Removing the auto-generated files from the project example is the only thing pending noted on the example repo. Will complete it after a final pass.  
Remove DataPaper-ReproducibilityWorkshop_files #9
https://github.com/UCSBCarpentry/Quarto-Project-Example/issues/9

**Closed as completed by rcurty** 2023-11-22 21:41 UTC
